name: ci
on:
  push:
    tags:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
jobs:
  package-box:
    name: Package Vagrant Boxes
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        box:
          - fbsd_13_2
          - fbsd_12_4
    steps:
      - name: Install Vagrant
        run: brew install vagrant
      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d
          key: ${{ matrix.box }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ matrix.box }}-vagrant-
      - uses: actions/checkout@v3
      - name: Set up VM
        run: |
          vagrant plugin install vagrant-disksize
          vagrant status
          vagrant up ${{ matrix.box }}
      - name: Package box
        run: |
          vagrant package ${{ matrix.box }} --output ${{ matrix.box }}.box
          ls -ahl *.box
      - name: Publish release
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.box }}.box
