name: ci
on:
  push:
    tags:
jobs:
  package-box:
    name: Package Vagrant Boxes
    runs-on: macos-10.15
    if: "startsWith(github.ref, 'refs/tags/')"
    strategy:
      matrix:
        box:
          #- fbsd_13_0
          - fbsd_12_2
    steps:
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d
          key: ${{ matrix.box }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ matrix.box }}-vagrant-
      - uses: actions/checkout@v2
      - name: Set up VM
        run: |
          vagrant plugin install vagrant-disksize
          vagrant up ${{ matrix.box }}
      - name: Package box
        run: |
          vagrant package ${{ matrix.box }} --output ${{ matrix.box }}.box
          ls -ahl *.box
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.box }}.box
